services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./build/docker/Dockerfile
    environment:
      - APPLICATION_PORT
      - GRIP_PROXY_HOST_NAME
      - GRIP_PROXY_PUBLISH_PORT
    ports:
      - "${APPLICATION_PORT}"
  grip-proxy:
    container_name: grip-proxy
    image: fanout/pushpin:1.33.1
    platform: linux/amd64
    volumes:
      - ./pushpin:/etc/pushpin
    ports:
      - "7999:7999"
      - "${GRIP_PROXY_PUBLISH_PORT}:5561"
